version: "2"

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/elmas
      - /elmas/node_modules
    ports:
      - "3001:3000"
    expose:
      -  "3001"
    env_file:
      - variables.env